apiVersion: v1
kind: Service
metadata:
  name: challenge-svc
  labels:
    app: challenge-svc
spec:
  selector:
    app: challenge 
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 8081
      targetPort: 80